Network Layout - Multi-tier Architecture - update secrets values

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -139,6 +139,24 @@ jobs:
 
       - name: Install Terraform
         run: |
+          set -e
+
+          # Get the directory where the script is located
+          SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+          # Navigate to the root directory of the project
+          ROOT_DIR="$(dirname "$SCRIPT_DIR")"
+
+          # Check if .env file exists in the root directory
+          if [ -f "$ROOT_DIR/.env" ]; then
+              # If the .env file exists, load the variables
+              source "$ROOT_DIR/.env"
+          else
+              # If .env file doesn't exist, print an error message and exit
+              echo "Error: .env file not found in the root directory."
+              exit 1
+          fi
+          
           chmod +x ./scripts/env/production/terraform.sh
           ./scripts/env/production/terraform.sh
 
